# Generated by Django 3.0.5 on 2020-04-27 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='', upload_to='image', verbose_name='图片')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
